# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='friends.User'),
        ),
    ]
